# Generated by Django 3.1.3 on 2021-05-17 16:50

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('color', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, null=True)),
                ('position', models.CharField(max_length=200)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.template')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True)),
                ('position', models.CharField(max_length=200)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.template')),
            ],
        ),
    ]
