# Generated by Django 3.1.3 on 2021-05-20 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20210519_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatetypeone',
            name='template_name',
        ),
        migrations.RemoveField(
            model_name='templatetypetwo',
            name='template_name',
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
