# Generated by Django 3.1.3 on 2021-05-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210520_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatetypeone',
            name='description_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatetypeone',
            name='description_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='templatetypeone',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatetypeone',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='templatetypeone',
            name='insta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatetypeone',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
