# Generated by Django 3.1.3 on 2021-05-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210520_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetypetwo',
            name='ablility_1_precent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='ablility_1_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='ablility_2_precent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='ablility_2_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='ablility_3_precent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='ablility_3_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='about_me_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='about_me_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='head_sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='head_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='img_6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='img_7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='img_9',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='more_info_1_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='more_info_1_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='more_info_2_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='more_info_2_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='more_info_3_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='more_info_3_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='more_info_4_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatetypetwo',
            name='more_info_4_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
