# Generated by Django 3.1.3 on 2021-05-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210521_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatetypetwo',
            old_name='img_9',
            new_name='img_8',
        ),
    ]
